image: python:3.6.7

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - pip3 install -e .
    - pip3 install -r requirements-test.txt
    - pip3 install -r requirements-optional.txt
  script:
    - make

deploy:
  stage: deploy
  only:
    - /^v\d+\.\d+\.\d+$/
  before_script:
    - pip3 install twine
  script:
    - python3 setup.py sdist
    - twine upload dist/* -u ${TWINE_USER} -p ${TWINE_PASSWORD}
